#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create tight-fitting background mesh
# runApplication blockMesh -region backgroundMeshDecomposition
# runApplication decomposePar -region backgroundMeshDecomposition

rm -r constant/backgroundMeshDecomposition/
cp system/snappyHexMeshSrc/* system/
runApplication ideasUnvToFoam backgroundMesh.unv
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite

# for d in processor*/; do
#     cd ${d%/}
#     mkdir -p constant/backgroundMeshDecomposition
#     mv constant/polyMesh constant/backgroundMeshDecomposition/polyMesh
#     cd ..
# done

runApplication reconstructParMesh -constant
rm -r log.decomposePar log.reconstructParMesh processor*

mkdir -p constant/backgroundMeshDecomposition
mv constant/polyMesh constant/backgroundMeshDecomposition/polyMesh
runApplication decomposePar -region backgroundMeshDecomposition

cp system/foamyHexMeshSrc/* system/
runParallel foamyHexMesh

runParallel -s collapseFaces \
    collapseEdges -latestTime -collapseFaces

runParallel -s collapseFaceSet \
    collapseEdges -latestTime -collapseFaceSet indirectPatchFaces

runParallel checkMesh -latestTime -allTopology -allGeometry

# runApplication reconstructParMesh -latestTime
runApplication reconstructParMesh


#------------------------------------------------------------------------------
